version: 2.0

jobs:
  "color":
    docker:
      - image: circleci/node:7.10
    working_directory: ~/container-playground/containers/color/
    steps:
      - checkout:
          path: ~/container-playground

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

  "mixer":
    docker:
      - image: circleci/node:7.10
    working_directory: ~/container-playground/containers/mixer/
    steps:
      - checkout:
          path: ~/container-playground

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - "color"
      - "mixer"